# Generated by Django 4.2.19 on 2025-03-05 19:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('full', 'Full Database Sync'), ('content', 'Content Sync'), ('media', 'Media Files Sync')], max_length=20)),
                ('source_instance', models.CharField(max_length=100)),
                ('target_instance', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('synced_items', models.IntegerField(default=0)),
                ('skipped_items', models.IntegerField(default=0)),
                ('sync_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synced_models', to='sync.synclog')),
            ],
        ),
    ]
